### ISSUE TITLE
Songs get skipped with no error message shown

### ISSUE THREAD

**Issue by nizeic** [nizeic/Noize#2]
I've done a few tests and noticed that this usually happens to the first songs in the queue
I also haven't noticed this happening on non-youtube links

found these 2 possible fixes:
https://github.com/Androz2091/discord-music-bot/issues/55#issuecomment-924105209
https://github.com/Androz2091/discord-music-bot/issues/24#issuecomment-922339568
will need some testing

**Comment by JoshCunningHum** [comment]
All right, I'll give some updates after testing some things, this is what I did so far

- tried to log every time the skip command is fired but no log is shown, which is natural, but the lack of errors made me do it
- tried to log the video details after firing the play command and video details are shown, so getting the video is operational. the playback must be the problem
- 

slow progress on my side though because of other stuff but I'll try to give this project some time after all of my chores are done

**Comment by nizeic** [comment]
> All right, I'll give some updates after testing some things, this is what I did so far
> 
> * tried to log every time the skip command is fired but no log is shown, which is natural, but the lack of errors made me do it
> * tried to log the video details after firing the play command and video details are shown, so getting the video is operational. the playback must be the problem
> 
> slow progress on my side though because of other stuff but I'll try to give this project some time after all of my chores are done

Thanks, but it looks like this is an issue with the dependencies.
Commit https://github.com/nizeic/Noize/commit/481059ce7d4a10f1f0009f0dacee3d803f0a1b3d should fix this for now, but I might switch back to the stable discord-player channel once they fix it

**Comment by nizeic** [comment]
Update: `queue.createStream` never gets called in https://github.com/nizeic/Noize/commit/481059ce7d4a10f1f0009f0dacee3d803f0a1b3d.
https://github.com/nizeic/Noize/commit/415c7d38dd7d942c8a5e65ce5232eb07610b4101 should fix this but I'll do more testing just in case and close this again in a few hours if confirmed.

**Comment by nizeic** [comment]
works fine, but it breaks support for non-youtube links since `source` always returns "youtube" for some reason even on spotify tracks (and possibly from other sites)
