### ISSUE TITLE
Playback control buttons

### ISSUE THREAD

**Issue by nizeic** [nizeic/Noize#3]
For easy playback control using buttons attached to the now-playing message embed in the `trackStart` event.

- [ ] play/pause button
- [ ] skip button
- [ ] queue list button
- [ ] disconnect/stop button

**Comment by JoshCunningHum** [comment]
I was working on this feature and I used the new [buttons](https://discordjs.guide/interactions/buttons.html#buttons) that discord.js provides because that is the only method I know of adding buttons. But unfortunately, discord buttons only support discord.js V12 and not the latest V13 as this is what it says here:
[Class extends value undefined](https://stackoverflow.com/questions/68972697/discord-bot-gets-an-error-becuase-class-extends-value-undefined-is-not-a-constr)
Although there is a fix as the answer stated, I don't know how to apply that :tired_face: (the [patch-package](https://www.npmjs.com/package/patch-package) method)
In case if you are downgrading discord.js, there might be some things that require changing (e.g. messageCreate -> message etc..)

But if you found other method, it would really help.

**Comment by nizeic** [comment]
>But unfortunately, discord buttons only support discord.js V12 and not the latest V13 as this is what it says here: [Class extends value undefined]

I think they're talking about the [discord-buttons](https://www.npmjs.com/package/discord-buttons) package which was made before discord.js v13 was released because there was no proper way to add buttons back then.


> I was working on this feature and I used the new [buttons](https://discordjs.guide/interactions/buttons.html#buttons) that discord.js provides because that is the only method I know of adding buttons.

In discord.js v13, this is a valid method to add buttons with no need for a separate package (like discord-buttons).

I've also tried following that tutorial last week for the next/previous buttons in the queue list command but I found it too confusing (and I was too lazy and didn't really understand how [Interactions](https://discord.js.org/#/docs/main/stable/class/Interaction) work) so I decided to install [a package to easily make paged embeds with buttons](https://www.npmjs.com/package/discordjs-button-pagination).

I'll try to help you with this once I'm done with #2 and my schoolwork :)
